# permissions for end users to view travellers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traveller-viewer-role
rules:
- apiGroups:
  - toys.ilkka.dev
  resources:
  - travellers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - toys.ilkka.dev
  resources:
  - travellers/status
  verbs:
  - get
